package tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import tests.models.Group;

public class GroupRemovalTests extends TestBase{

    @Test
    public void canRemoveGroup() {
        openGroupsPage();
        if (!isGroupPresent()) {
            createGroup(new Group("name", "header", "footer"));
            returnToGroupPage();
        }
        removeGroup();

    }

}
