package ru.stqa.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.models.Group;

public class GroupRemovalTests extends TestBase {

    @Test
    public void canRemoveGroup() {
        if (!app.groups().isGroupPresent()) {
            app.groups().createGroup(new Group("name", "header", "footer"));
        }
        app.groups().removeGroup();

    }

}
