package ru.stqa.addressbook.tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.models.Group;

public class GroupRemovalTests extends TestBase {

    @Test
    public void canRemoveGroup() {
        app.openGroupsPage(GroupRemovalTests.this);
        if (!app.isGroupPresent(GroupRemovalTests.this)) {
            app.createGroup(new Group("name", "header", "footer"));
            app.returnToGroupPage();
        }
        app.removeGroup();

    }

}
